/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WheelchairRouteImport } from './routes/wheelchair'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as CorsiRouteImport } from './routes/corsi'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ClubRouteImport } from './routes/club'
import { Route as IndexRouteImport } from './routes/index'

const WheelchairRoute = WheelchairRouteImport.update({
  id: '/wheelchair',
  path: '/wheelchair',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const CorsiRoute = CorsiRouteImport.update({
  id: '/corsi',
  path: '/corsi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/contatti': typeof ContattiRoute
  '/corsi': typeof CorsiRoute
  '/servizi': typeof ServiziRoute
  '/wheelchair': typeof WheelchairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/contatti': typeof ContattiRoute
  '/corsi': typeof CorsiRoute
  '/servizi': typeof ServiziRoute
  '/wheelchair': typeof WheelchairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/contatti': typeof ContattiRoute
  '/corsi': typeof CorsiRoute
  '/servizi': typeof ServiziRoute
  '/wheelchair': typeof WheelchairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/club' | '/contatti' | '/corsi' | '/servizi' | '/wheelchair'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/club' | '/contatti' | '/corsi' | '/servizi' | '/wheelchair'
  id:
    | '__root__'
    | '/'
    | '/club'
    | '/contatti'
    | '/corsi'
    | '/servizi'
    | '/wheelchair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubRoute: typeof ClubRoute
  ContattiRoute: typeof ContattiRoute
  CorsiRoute: typeof CorsiRoute
  ServiziRoute: typeof ServiziRoute
  WheelchairRoute: typeof WheelchairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wheelchair': {
      id: '/wheelchair'
      path: '/wheelchair'
      fullPath: '/wheelchair'
      preLoaderRoute: typeof WheelchairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corsi': {
      id: '/corsi'
      path: '/corsi'
      fullPath: '/corsi'
      preLoaderRoute: typeof CorsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubRoute: ClubRoute,
  ContattiRoute: ContattiRoute,
  CorsiRoute: CorsiRoute,
  ServiziRoute: ServiziRoute,
  WheelchairRoute: WheelchairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
